package com.example.data.flood

import com.example.data.model.AlertSeverity

/**
 * Water-level trend observed at the river gauge station.
 */
enum class WaterLevelTrend(val displayName: String, val arrowSymbol: String) {
    RISING("Rising", "▲"),
    FALLING("Falling", "▼"),
    STEADY("Steady", "▶")
}

/**
 * Authoritative classification by Central Water Commission (CWC)
 * & State Flood Management Information System (FMIS).
 */
enum class FloodRiskCategory(
    val title: String,
    val severity: AlertSeverity,
    val priorityRank: Int, // 1 is highest priority
    val colorHex: Long
) {
    SEVERE_FLOOD_RISK("Severe Flood Risk", AlertSeverity.RED, 1, 0xFFDC2626), // > DL + 0.5m or > HFL
    DANGER("Above Danger Level", AlertSeverity.RED, 1, 0xFFEF4444),           // >= DL
    WARNING("Above Warning Level", AlertSeverity.ORANGE, 3, 0xFFF97316),       // >= WL
    WATCH("Flood Watch / Approaching", AlertSeverity.YELLOW, 4, 0xFFEAB308),   // Approaching WL + rain
    NORMAL("Normal River Flow", AlertSeverity.GREEN, 6, 0xFF10B981)            // Well below WL
}

/**
 * Authoritative River Monitoring Gauge Station Model.
 * Anchored to official CWC & Bihar Water Resources Department (WRD) benchmark levels.
 */
data class RiverBasinStation(
    val stationId: String,
    val stationName: String,
    val riverName: String,
    val basinName: String,
    val district: String,
    val state: String,
    val latitude: Double,
    val longitude: Double,
    val warningLevelM: Double,       // Warning Level in meters above MSL
    val dangerLevelM: Double,        // Danger Level in meters above MSL
    val highestFloodLevelM: Double,  // Highest Flood Level (HFL) recorded
    val upstreamStationId: String? = null,
    val primaryAgency: String = "CWC / Bihar WRD FMIS"
)

/**
 * Real observation record containing telemetry and meteorological inputs.
 */
data class RiverObservation(
    val stationId: String,
    val timestamp: Long,
    val observationTimeFormatted: String,
    val currentWaterLevelM: Double,
    val warningLevelM: Double,
    val dangerLevelM: Double,
    val highestFloodLevelM: Double,
    val trend: WaterLevelTrend,
    val rainfallIntensityMm: Double,      // 24h observed rainfall in catchment
    val forecastRainfallMm: Double,       // 24h-48h forecast rainfall from NWP/IMD
    val source: String,
    val isAuthoritativeFeed: Boolean = true,
    val upstreamWaterLevelStatus: String? = null
)

/**
 * Computed Flood Risk Output from the deterministic Risk Engine.
 * Note: NEVER generated by LLM reasoning. Strictly calculated from numeric telemetry.
 */
data class FloodRiskAssessment(
    val station: RiverBasinStation,
    val observation: RiverObservation,
    val currentLevelRatioDanger: Double,     // current_level / danger_level
    val currentLevelRatioWarning: Double,    // current_level / warning_level
    val distanceAboveWarningM: Double,       // current_level - warning_level
    val distanceAboveDangerM: Double,        // current_level - danger_level
    val classification: FloodRiskCategory,
    val urgencyLevel: AlertSeverity,
    val statusText: String,
    val priorityRank: Int,
    val upstreamRiskPresent: Boolean,
    val recommendedAction: String,
    val recommendedActionHindi: String,
    val voiceAnnouncementEnglish: String,
    val voiceAnnouncementHindi: String,
    val calculatedAt: Long = System.currentTimeMillis()
)

/**
 * State container for flood feed status & failure handling.
 */
sealed class FloodMonitoringState {
    data class Active(
        val assessments: List<FloodRiskAssessment>,
        val lastObservationTimestamp: Long,
        val sourceAttribution: String
    ) : FloodMonitoringState()

    data class Unavailable(
        val message: String = "Flood monitoring data temporarily unavailable.",
        val lastSuccessfulTimestamp: Long? = null
    ) : FloodMonitoringState()
}
